server:
  port: 8765

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
    # cloud:
      # gateway:
      # discovery:
      # locator:
      #  enabled: true
    # lower-case-service-id: true